package me.dmadouros.pokerhand.infrastructure

import me.dmadouros.pokerhand.domain.model.Action
import me.dmadouros.pokerhand.domain.model.Hand
import me.dmadouros.pokerhand.domain.model.Position
import me.dmadouros.pokerhand.domain.model.PreviousAction

class Database {
    private data class Row(
        val hand: String,
        val previousAction: PreviousAction,
        val position: Position,
        val action: Action,
    )

    private val rows =
        setOf(
            Row("AA", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("KK", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("QQ", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("JJ", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("TT", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("AKs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("AQs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("AJs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("ATs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("KQs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("AK", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("AQ", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Row("99", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Row("88", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Row("77", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Row("KJs", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Row("QJs", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Row("AJ", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Row("KQ", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Row("AA", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("KK", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("QQ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("JJ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("TT", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("99", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("AKs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("AQs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("AJs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("ATs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("KQs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("KJs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("AK", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("AQ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("AJ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("KQ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Row("88", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("77", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("66", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("55", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("44", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("33", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("22", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("A9s", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("A8s", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("A7s", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("KTs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("QJs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("QTs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("JTs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("AT", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("KJ", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Row("AA", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("KK", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("QQ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("JJ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("TT", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("99", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("88", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("AKs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("AQs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("AJs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("ATs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("A9s", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("A8s", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("KQs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("KJs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("KTs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("QJs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("AK", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("AQ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("AJ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("AT", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("KQ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("KJ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Row("77", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("66", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("55", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("44", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("33", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("22", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("A7s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("A6s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("A5s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("A4s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("A3s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("A2s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("K9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("QTs", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("Q9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("JTs", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("T9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("98s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("87s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("J9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("T8s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Row("AA", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("KK", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("QQ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("JJ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("TT", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("99", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AKs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AQs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AJs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("ATs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("KQs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("KJs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AK", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AQ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AJ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("KQ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("88", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("77", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("66", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("55", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("44", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("33", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("22", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A7s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A6s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A5s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A4s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A3s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("A2s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("KTs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("K9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("K8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("QJs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("QTs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("Q9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("Q8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("JTs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("T9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("98s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("87s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("76s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("54s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("J9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("T8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("AT", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("KJ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Row("AA", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("KK", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("QQ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("JJ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("TT", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("99", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AKs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AQs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AJs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("ATs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("KQs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("KJs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AK", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AQ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AJ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("KQ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AA", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("KK", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("QQ", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("JJ", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("TT", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("AKs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("AQs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("AJs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("KQs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("AK", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Row("AA", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("KK", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("QQ", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("JJ", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("TT", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("AKs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("AQs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("AJs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("KQs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("AK", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Row("AA", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("KK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("QQ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("JJ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("TT", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AKs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AJs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("KQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AA", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("KK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("QQ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("JJ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("TT", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AKs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AJs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("KQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Row("AA", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("KK", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("QQ", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("JJ", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("TT", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AKs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AQs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AJs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("KQs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AK", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AA", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Row("KK", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Row("QQ", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Row("JJ", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AKs", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AQs", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AK", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Row("TT", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("99", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("88", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("77", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("66", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("55", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("44", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("33", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("22", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("AJs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("ATs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A8s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A7s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A6s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A5s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A4s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A3s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("A2s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("KQs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("KJs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("KTs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("K9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("QJs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("QTs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("Q9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("JTs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("T9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("98s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("87s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("J9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("T8s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("AQ", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Row("AA", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Row("KK", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Row("QQ", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Row("AKs", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Row("AA", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Row("KK", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Row("QQ", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Row("AKs", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Row("AA", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Row("KK", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Row("QQ", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Row("AKs", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Row("AA", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("KK", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("QQ", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AKs", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Row("AA", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
            Row("KK", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
            Row("QQ", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
            Row("AKs", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
        )

    fun findAction(
        position: Position,
        previousAction: PreviousAction,
        hand: Hand,
    ): Action {
        val default =
            if (position == Position.BIG_BLIND && previousAction == PreviousAction.UNRAISED) {
                Action.CHECK
            } else {
                Action.FOLD
            }

        return rows
            .find { row ->
                row.position == position &&
                    row.previousAction == previousAction &&
                    row.hand == hand.toHandType()
            }?.action ?: default
    }
}