package me.dmadouros.pokerhand.infrastructure

import me.dmadouros.pokerhand.domain.model.Action
import me.dmadouros.pokerhand.domain.model.Hand
import me.dmadouros.pokerhand.domain.model.Position
import me.dmadouros.pokerhand.domain.model.PreviousAction
import me.dmadouros.pokerhand.domain.model.RuleSet

class LimitRuleSet : RuleSet {
    private data class Rule(
        val hand: String,
        val previousAction: PreviousAction,
        val position: Position,
        val action: Action,
    )

    private val rules =
        setOf(
            Rule("AA", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("KK", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("QQ", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("JJ", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("TT", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("AKs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("AQs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("AJs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("ATs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("KQs", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("AK", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("AQ", PreviousAction.UNRAISED, Position.EARLY, Action.RAISE),
            Rule("99", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Rule("88", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Rule("77", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Rule("KJs", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Rule("QJs", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Rule("AJ", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Rule("KQ", PreviousAction.UNRAISED, Position.EARLY, Action.CALL),
            Rule("AA", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("KK", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("QQ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("JJ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("TT", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("99", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("AKs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("AQs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("AJs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("ATs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("KQs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("KJs", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("AK", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("AQ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("AJ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("KQ", PreviousAction.UNRAISED, Position.MIDDLE, Action.RAISE),
            Rule("88", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("77", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("66", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("55", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("44", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("33", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("22", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("A9s", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("A8s", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("A7s", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("KTs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("QJs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("QTs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("JTs", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("AT", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("KJ", PreviousAction.UNRAISED, Position.MIDDLE, Action.CALL),
            Rule("AA", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("KK", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("QQ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("JJ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("TT", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("99", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("88", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("AKs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("AQs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("AJs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("ATs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("A9s", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("A8s", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("KQs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("KJs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("KTs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("QJs", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("AK", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("AQ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("AJ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("AT", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("KQ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("KJ", PreviousAction.UNRAISED, Position.LATE, Action.RAISE),
            Rule("77", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("66", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("55", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("44", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("33", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("22", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("A7s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("A6s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("A5s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("A4s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("A3s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("A2s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("K9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("QTs", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("Q9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("JTs", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("T9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("98s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("87s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("J9s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("T8s", PreviousAction.UNRAISED, Position.LATE, Action.CALL),
            Rule("AA", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("KK", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("QQ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("JJ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("TT", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("99", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AKs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AQs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AJs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("ATs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("KQs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("KJs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AK", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AQ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AJ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("KQ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("88", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("77", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("66", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("55", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("44", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("33", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("22", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A7s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A6s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A5s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A4s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A3s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("A2s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("KTs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("K9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("K8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("QJs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("QTs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("Q9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("Q8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("JTs", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("T9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("98s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("87s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("76s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("54s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("J9s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("T8s", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("AT", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("KJ", PreviousAction.UNRAISED, Position.SMALL_BLIND, Action.CALL),
            Rule("AA", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("KK", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("QQ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("JJ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("TT", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("99", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AKs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AQs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AJs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("ATs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("KQs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("KJs", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AK", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AQ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AJ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("KQ", PreviousAction.UNRAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AA", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("KK", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("JJ", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("TT", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("AQs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("AJs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("KQs", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("AK", PreviousAction.RAISED, Position.EARLY, Action.RAISE),
            Rule("AA", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("KK", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("JJ", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("TT", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("AQs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("AJs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("KQs", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("AK", PreviousAction.RAISED, Position.MIDDLE, Action.RAISE),
            Rule("AA", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("KK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("JJ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("TT", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AJs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("KQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AA", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("KK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("JJ", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("TT", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AJs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("KQs", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AK", PreviousAction.RAISED, Position.LATE, Action.RAISE),
            Rule("AA", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("KK", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("JJ", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("TT", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AQs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AJs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("KQs", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AK", PreviousAction.RAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AA", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("KK", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("JJ", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AQs", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AK", PreviousAction.RAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("TT", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("99", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("88", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("77", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("66", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("55", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("44", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("33", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("22", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("AJs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("ATs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A8s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A7s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A6s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A5s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A4s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A3s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("A2s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("KQs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("KJs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("KTs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("K9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("QJs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("QTs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("Q9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("JTs", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("T9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("98s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("87s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("J9s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("T8s", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("AQ", PreviousAction.RAISED, Position.BIG_BLIND, Action.CALL),
            Rule("AA", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Rule("KK", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED_AND_RERAISED, Position.EARLY, Action.RAISE),
            Rule("AA", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Rule("KK", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED_AND_RERAISED, Position.MIDDLE, Action.RAISE),
            Rule("AA", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Rule("KK", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED_AND_RERAISED, Position.LATE, Action.RAISE),
            Rule("AA", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("KK", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED_AND_RERAISED, Position.SMALL_BLIND, Action.RAISE),
            Rule("AA", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("KK", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("QQ", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
            Rule("AKs", PreviousAction.RAISED_AND_RERAISED, Position.BIG_BLIND, Action.RAISE),
        )

    override fun findAction(
        position: Position,
        previousAction: PreviousAction,
        hand: Hand,
    ): Action {
        val default =
            if (position == Position.BIG_BLIND && previousAction == PreviousAction.UNRAISED) {
                Action.CHECK
            } else {
                Action.FOLD
            }

        return rules
            .find { rule ->
                rule.position == position &&
                    rule.previousAction == previousAction &&
                    rule.hand == hand.toHandType()
            }?.action ?: default
    }
}